version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${POSTGRES_PORT}'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
